"
notice: Copyright 2013,2016 GemTalk Systems, LLC. Open source under the MIT license.
category: accessing options
"
packageByCategory
	"Should we scan the image for class categories and method protocols
	to determine what package things belong in?
	Must be true unless you have newer tools that are Cypress-aware
	or are running on a platform that already has a package notion."

	^packageByCategory