Class {
	#name : 'RwReferenceSpecification',
	#superclass : 'RwSpecification',
	#instVars : [
		'referenceUrl'
	],
	#category : 'Rowan-Core'
}

{ #category : 'accessing' }
RwReferenceSpecification >> referenceUrl [

   ^referenceUrl

]

{ #category : 'accessing' }
RwReferenceSpecification >> referenceUrl: anObject [

   referenceUrl := anObject

]

{ #category : 'actions' }
RwReferenceSpecification >> resolve [
]
