Extension { #name : 'RwAbstractProjectLoadComponentV2' }

{ #category : '*rowan-gsbase-componentsv2' }
RwAbstractProjectLoadComponentV2 class >> fromFile: filePath [
	self error: 'Not yet implemented'
]

{ #category : '*rowan-gsbase-componentsv2' }
RwAbstractProjectLoadComponentV2 class >> orderedDictionaryClass [

	^ GsTonelOrderedDictionary
]

{ #category : '*rowan-gsbase-componentsv2' }
RwAbstractProjectLoadComponentV2 >> _exportToUrl: fileUrl [
	self error: 'Not yet implemented'
]
