Class {
	#name : 'RwGsMethodExtensionSessionMethodPropertiesSymDictPatchV2',
	#superclass : 'RwGsMethodPropertiesSymDictPatchV2',
	#category : 'Rowan-GemStone-LoaderV2'
}

{ #category : 'installing' }
RwGsMethodExtensionSessionMethodPropertiesSymDictPatchV2 >> installPropertiesPatchNewClasses: createdClasses andExistingClasses: tempSymbols [

	^ super installPropertiesPatchNewClasses: createdClasses andExistingClasses: tempSymbols

]
