Class {
	#name : 'RowanResolvedProjectService',
	#superclass : 'RowanProjectService',
	#category : 'Rowan-Services-Core'
}

{ #category : 'client commands' }
RowanResolvedProjectService >> define [
]

{ #category : 'client commands' }
RowanResolvedProjectService >> load [
]

{ #category : 'client commands' }
RowanResolvedProjectService >> read [
]

{ #category : 'client commands' }
RowanResolvedProjectService >> write [
]
